# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77e296a303f16d0d888db4613f99a85f14b2643e7b7f25f13d0cd04b0c33f72a4179d9ad8559c20294ec97f0755c0130a2a3f8de66b75c4fc9909573954949fc

test:
  secret_key_base: 246b91d0f41bb5e11105ea920b6eb3aa42077fd785b534722323f1f0dd74af8cc3d4a27a38d16da2780922159d256813d87c3bbdfe09fba9e7a948eff95c85f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
